"""
Django settings for opm project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import cloudinary_storage
# import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a&b81*@0h=&035ho$$jhbvd=62abat-rh1)u17+kvtqj(jzuh4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '.now.sh', '127.0.0.1']
# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'opmApp',
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'opm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opm.wsgi.application'




# postgres://avnadmin:AVNS_EhBGgBs84ma2m0AW9qP@pg-4e91638-opms.l.aivencloud.com:27207/defaultdb?sslmode=require


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': dj_database_url.config{
#         'ENGINE': 'django_cockroachdb',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASE_URL = "postgresql://blessing:rWEf27wCcy9ID-eLyV70Mw@opmsdatabase-15955.8nj.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full"

# DATABASES = {
#     'default': dj_database_url.parse(DATABASE_URL, engine='django_cockroachdb')
# }



# # ============================= MONGO DATABASES ===========
# import ssl
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'OPMS',
#         'ENFORCE_SCHEMA': False,
#         'CLIENT': {
#             'host': 'mongodb+srv://olamidedevops:TKgHFlQD4MtqpDYa@auth.nleripr.mongodb.net/OPMS?retryWrites=true&w=majority&ssl=true',
#             'ssl': True,
#             'username': 'olamidedevops',
#             'password': 'TKgHFlQD4MtqpDYa',
#             'authMechanism': 'SCRAM-SHA-1',
#             # 'ssl_cert_reqs': ssl.CERT_NONE,
#             'tlsAllowInvalidCertificates': True,
#             'tls': True,
#             'socketTimeoutMS': 100000,
#             'connectTimeoutMS': 100000,
            
#         }
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'defaultdb', 
        'USER': 'avnadmin',   
        'PASSWORD': 'AVNS_EhBGgBs84ma2m0AW9qP',  
        'HOST': 'pg-4e91638-opms.l.aivencloud.com',
        'PORT': '27207',
        'OPTIONS': {
            'sslmode': 'require', 
            # 'sslrootcert': 'system',
        },
    }
}



# -----BEGIN CERTIFICATE-----
# MIIEQTCCAqmgAwIBAgIUd0FFELwrafVMwnN6wHwQCKGXdOYwDQYJKoZIhvcNAQEM
# BQAwOjE4MDYGA1UEAwwvMWZiMjA3OTctOWQzNy00YjE3LTgzOTUtNGYyMjkwOTlj
# ZGUzIFByb2plY3QgQ0EwHhcNMjQwODA5MDYxMzUzWhcNMzQwODA3MDYxMzUzWjA6
# MTgwNgYDVQQDDC8xZmIyMDc5Ny05ZDM3LTRiMTctODM5NS00ZjIyOTA5OWNkZTMg
# UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMufSJwk
# jRO30bok31UYZshMTTa2NcXue6EzP1ElltgHQKfd5cZZM7hLzAlTuFRteACWYLWN
# A/0juy9qhJ7OeKZAbarcZdbdoWKbujCaOG/2uahMQMMyivVcHOj1IKvVCz/ZbljV
# zX4MF/xtts+UyDMj4ip1pX+EPVk4hqG+7TOZUtXS4tyxEen5NS/2/Wnk7zucSJgD
# OwzFJeYWu6//ORzLVXmAy2opnmB0qTWNiZhQOEOihwvci6GV/f6o9JlqwuSUvhIA
# oCBC73SzDImo1N3L0aZ4/3DnJen+89wkFy7hdPUrAmwsBdjTeuobxrUMaCsCxuMr
# p475SZYqAGEkStgnbwML6Vyy4+UUw2jvirLoIm3KM5tb0ro7vj7ud84BuAqi79AX
# 1vIE9+209JqH2CCi6byHDTTQZ6NnEoAyg0pAiraNBOkTlLgkU8yBtZHCZe5s5DRG
# inJQWn8B5Oxk4gq5mJ/70e+v6J0jrI+pAxnsFlduoCiS9bOOJi7JfDwCjwIDAQAB
# oz8wPTAdBgNVHQ4EFgQUDjXsF/K5C8C+bplQJAGHXfgi/E0wDwYDVR0TBAgwBgEB
# /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAFGZAeZVgvx+EYmS
# vWmGE6kuFXAj2ksp50vnQ/Jhdqo+m5x/UuNcE4sKpaIQ67efLS22bNyLQp515WyJ
# +pz0sxcPS5Xe4+T4by4pAY/EzX8GOfDnrTf/5zF4AMlV2Re/+NbuDmIQFYfllOZ5
# a7zK1GU8P66M2Zlju18/M27GJz3MPfMMLhxfYXyH8okgeGKgpdFItRlgANl5RUAB
# NDrDhLzoY9jWMpkZY3B44XKQdICHp2/fGLS/12aEjcC/ETfKk0JIrgrgYd7Uevw9
# R+3Gegfpukfu8yRmNT/iqS8WDAnp+jl1gVThFn0ed1hsY+A5dbq4gAQ8mBKiAwe2
# ciOfKHBRuqYQEEyEMWwH/N3/wlTyFLyqh9+sLux2fI00riuKJTClhuuCdMnslrYP
# PX2zKkhkw44PzoPimQJVmYPERDpxdMAjNmwp0UDhirlYlTc/99O91PSOPxZneL4j
# WefXxz2e52ct/GtiAHR0SFG97otqXy8Jm0gQG1fYi11oDUSHpg==
# -----END CERTIFICATE-----


# DATABASES = {'default': dj_database_url.config(default=os.environ['DATABASE_URL'], engine='django_cockroachdb')}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIR = os.path.join(BASE_DIR, 'static'),
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'opmApp.CustomUser'




# +================================ CODE FOR EMAIL NOTIFICAION ======================

EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend' # the email backend is a fixed you must put it exactly how you see it
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER='adeblessinme4u@gmail.com' #Your email address will be here i.e the sender email address
EMAIL_HOST_PASSWORD ='qvpx txbb mrji blpz' #the Email Host Password you will put your App Password since google don't allow "less secure app", you can find or create app password in your google account by navigating to security then search for App password, then you can create or copy the password there.




AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
    'opmApp.backends.PatientBackend',  # Custom backend
]



# FOR IMAGE OR FILE UPLOADING...

MEDIA_ROOT= 'static/opms'
MEDIA_URL='/opms/'


CLOUDINARY_STORAGE={
    'CLOUD_NAME': 'dbqtos6rt',
    'API_KEY': '688616267922488',
    'API_SECRET': '1vX0m1yd1ihW-8vfWkv3pep4nfw'
}

DEFAULT_FILE_STORAGE ='cloudinary_storage.storage.MediaCloudinaryStorage'



JAZZMIN_SETTINGS ={
    "site_title": "OPMS",
    "site_header": "OPMS ADMINISTRATION",
    "site_brand": "OPMS ADMINISTRATION",
    "copyright": "LUTH",
    "site_logo": "https://res.cloudinary.com/dbqtos6rt/image/upload/v1720673537/opms/assets/logo_iueamp.png",
}