# Generated by Django 4.2.13 on 2024-05-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0002_department_doctor_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialist',
        ),
    ]
