# Generated by Django 4.2.13 on 2024-05-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='describtion',
            new_name='description',
        ),
    ]
