# Generated by Django 4.2.13 on 2024-05-29 02:39

from django.db import migrations, models
import django.utils.timezone
import opmApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0007_appointment_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('recordNumber', models.CharField(max_length=12, unique=True)),
                ('assignedDoctorName', models.CharField(max_length=40, verbose_name=opmApp.models.Doctor)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('condition_before', models.CharField(max_length=100, null=True)),
                ('condition_after', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('dischargeMeditations', models.CharField(max_length=200)),
                ('dischargeInstructions', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_note',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
