# Generated by Django 4.2.13 on 2024-05-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0010_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
