# Generated by Django 4.2.13 on 2024-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0011_alter_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
