# Generated by Django 4.2.13 on 2024-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0012_alter_appointment_condition_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
