# Generated by Django 4.2.13 on 2024-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0017_alter_appointment_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
