# Generated by Django 4.2.13 on 2024-07-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0018_alter_appointment_date_time_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='---', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='---', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, default='---'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/profile_bgrbul.jpg', upload_to='profile/'),
        ),
    ]
