# Generated by Django 4.2.13 on 2024-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0019_remove_patient_address_remove_patient_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
