# Generated by Django 4.2.13 on 2024-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0020_alter_customuser_address_alter_customuser_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(default=2),
        ),
    ]
