# Generated by Django 4.2.13 on 2024-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0021_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(default='Nigeria', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_documents/'),
        ),
    ]
