# Generated by Django 4.2.13 on 2024-07-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0022_doctor_country_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dbqtos6rt/image/upload/v1720589104/opms/profile/profile_bgrbul.jpg', upload_to='profile/'),
        ),
    ]
