# Generated by Django 4.2.13 on 2024-07-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0024_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresult',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='opmApp.patient'),
        ),
    ]
