# Generated by Django 4.2.13 on 2024-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0025_medicalresult_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=20),
        ),
    ]
