# Generated by Django 4.2.13 on 2024-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0026_remove_doctor_country_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
