# Generated by Django 4.2.13 on 2024-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0027_patient_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalresult',
            name='recordNumber',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
