# Generated by Django 4.2.14 on 2024-07-21 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0029_remove_medicalresult_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalresult',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='medicalresult',
            name='recordNumber',
        ),
        migrations.AddField(
            model_name='medicalresult',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='OtherCharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='doctorFee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='medicineCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='roomCharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
