# Generated by Django 4.2.14 on 2024-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0030_remove_medicalresult_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalresult',
            name='address',
        ),
        migrations.AddField(
            model_name='medicalresult',
            name='history_of_illness',
            field=models.TextField(blank=True, default='Not Applicable'),
        ),
    ]
