# Generated by Django 4.2.14 on 2024-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0031_remove_medicalresult_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalresult',
            name='dischargeMeditations',
            field=models.TextField(default='Not Applicable'),
        ),
    ]
