# Generated by Django 4.2.14 on 2024-07-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0032_alter_medicalresult_dischargemeditations'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresult',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='opmApp.doctor'),
        ),
    ]
