# Generated by Django 4.2.14 on 2024-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0033_medicalresult_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalresult',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
