# Generated by Django 4.2.14 on 2024-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0034_medicalresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalresult',
            name='daySpent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
