# Generated by Django 4.2.14 on 2024-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0039_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
