# Generated by Django 4.1.13 on 2024-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0040_alter_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctoravailableday',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='invoice_id',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
        ),
    ]
