# Generated by Django 4.1.13 on 2024-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0041_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalresult',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
