# Generated by Django 4.1.13 on 2024-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0042_alter_appointment_date_time_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default=2, max_length=50),
        ),
    ]
