# Generated by Django 4.1.13 on 2024-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0043_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='opms/profile/profile_bgrbul.jpg', upload_to='profile/'),
        ),
    ]
