# Generated by Django 5.0 on 2024-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opmApp', '0045_alter_appointment_date_time_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(max_length=50),
        ),
    ]
